#!/usr/bin/env php
<?php

error_reporting(E_ALL);
setlocale(LC_CTYPE, "en_US.UTF-8");

$timezone = ini_get('date.timezone');
if (empty($timezone)) {
    date_default_timezone_set('Europe/Berlin');
}

include __DIR__.'/vendor/autoload.php';

/** @var \Monolog\Logger $log */
$log = include_once __DIR__.'/src/logger.php';
include_once __DIR__.'/src/helper.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \RhFlow\Thumbnailer\MP4Command($log['mp4']));
$application->add(new \RhFlow\Thumbnailer\NEFCommand($log['nef']));
$application->add(new \RhFlow\Thumbnailer\CleanupCommand($log['cleanup']));

$application->run();